import io
from datetime import datetime


# ════════════════════════════════════════════════
#  WORD DOCUMENT EXPORT
# ════════════════════════════════════════════════
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_word_doc(summary: str, filename: str) -> bytes:
    '''
    Creates a formatted Word document from summary.
    Returns document as bytes for HTTP download.
    filename = original PDF name e.g. BhattacharyaDistance.pdf
    '''
    doc = DocxDocument()

    # Page margins
    sec = doc.sections[0]
    sec.top_margin    = Inches(1)
    sec.bottom_margin = Inches(1)
    sec.left_margin   = Inches(1.2)
    sec.right_margin  = Inches(1.2)

    # Title
    title = doc.add_heading('Document Summary', level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if title.runs:
        title.runs[0].font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)

    # Metadata
    doc.add_paragraph()
    table = doc.add_table(rows=2, cols=2)
    table.style = 'Table Grid'
    meta = [
        ('Source File', filename),
        ('Generated On', datetime.now().strftime('%d %B %Y, %I:%M %p')),
    ]
    for i, (label, value) in enumerate(meta):
        row = table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = value
        if row.cells[0].paragraphs[0].runs:
            row.cells[0].paragraphs[0].runs[0].bold = True

    doc.add_paragraph()
    doc.add_heading('Summary', level=2)

    # Summary body
    body = doc.add_paragraph(summary)
    body.paragraph_format.space_after = Pt(6)

    # Footer
    footer_para = doc.sections[0].footer.paragraphs[0]
    footer_para.text = 'Generated by AI Office Assistant'
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


# ════════════════════════════════════════════════
#  PDF EXPORT
# ════════════════════════════════════════════════
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph as RLParagraph,
    Spacer,
    Table as RLTable,
    TableStyle
)

def generate_pdf(summary: str, filename: str) -> bytes:
    '''
    Creates a clean PDF from summary.
    Returns PDF as bytes for HTTP download.
    '''
    buffer = io.BytesIO()
    pdf = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=inch, bottomMargin=inch,
        leftMargin=1.2*inch, rightMargin=1.2*inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('Title2', parent=styles['Title'],
        fontSize=20, textColor=colors.HexColor('#1F4E79'),
        spaceAfter=14, alignment=1)

    label_style = ParagraphStyle('Label', parent=styles['Normal'],
        fontSize=10, textColor=colors.HexColor('#2E75B6'),
        fontName='Helvetica-Bold')

    body_style = ParagraphStyle('Body', parent=styles['Normal'],
        fontSize=12, leading=18, spaceAfter=8)

    story = []
    story.append(RLParagraph('Document Summary', title_style))
    story.append(Spacer(1, 0.2*inch))

    # Metadata table
    meta_data = [
        ['Source File', filename],
        ['Generated', datetime.now().strftime('%d %B %Y, %I:%M %p')],
    ]
    meta_tbl = RLTable(meta_data, colWidths=[1.5*inch, 4*inch])
    meta_tbl.setStyle(TableStyle([
        ('BACKGROUND',  (0,0), (0,-1), colors.HexColor('#EEF4FB')),
        ('FONTNAME',    (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTSIZE',    (0,0), (-1,-1), 10),
        ('GRID',        (0,0), (-1,-1), 0.5, colors.HexColor('#CCCCCC')),
        ('PADDING',     (0,0), (-1,-1), 6),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 0.3*inch))
    story.append(RLParagraph('Summary', label_style))
    story.append(Spacer(1, 0.1*inch))

    for line in summary.split('\n'):
        if line.strip():
            story.append(RLParagraph(line.strip(), body_style))

    pdf.build(story)
    buffer.seek(0)
    return buffer.read()
