import 'dart:typed_data';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:share_plus/share_plus.dart';

import 'package:path_provider/path_provider.dart'
if (dart.library.html) 'package:ai_office_app/stubs/path_provider_stub.dart';
import 'package:open_file/open_file.dart'
if (dart.library.html) 'package:ai_office_app/stubs/open_file_stub.dart';
import 'dart:io'
if (dart.library.html) 'package:ai_office_app/stubs/io_stub.dart';

import 'api_service.dart';

class ExportService {

  static String get _baseUrl => ApiService.baseUrl;

  // ════════════════════════════════════════════
  //  WORD EXPORT
  // ════════════════════════════════════════════
  static Future<String> exportAsWord({
    required String summary,
    required String filename,
  }) async {
    final response = await http.post(
      Uri.parse('$_baseUrl/export/word'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({'summary': summary, 'filename': filename}),
    ).timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('Word export failed: ${response.statusCode}');
    }

    return _saveAndOpen(response.bodyBytes, 'summary.docx');
  }

  // ════════════════════════════════════════════
  //  PDF EXPORT
  // ════════════════════════════════════════════
  static Future<String> exportAsPdf({
    required String summary,
    required String filename,
  }) async {
    final response = await http.post(
      Uri.parse('$_baseUrl/export/pdf'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({'summary': summary, 'filename': filename}),
    ).timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('PDF export failed: ${response.statusCode}');
    }

    return _saveAndOpen(response.bodyBytes, 'summary.pdf');
  }

  // ════════════════════════════════════════════
  //  PLAIN TEXT EXPORT
  // ════════════════════════════════════════════
  static Future<String> exportAsText({
    required String summary,
    required String filename,
  }) async {
    final now = DateTime.now();
    final content = '''DOCUMENT SUMMARY
================
Source File  : $filename
Generated On : ${now.day}/${now.month}/${now.year}  ${now.hour}:${now.minute.toString().padLeft(2, '0')}
Generated By : AI Office Assistant

SUMMARY
-------
$summary
''';

    if (kIsWeb) {
      await SharePlus.instance.share(
        ShareParams(text: content, subject: 'Document Summary — $filename'),
      );
      return 'shared';
    }

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/summary.txt');
    await file.writeAsString(content);

    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path)],
        text: 'Document Summary — $filename',
      ),
    );
    return file.path;
  }

  // ════════════════════════════════════════════
  //  INTERNAL: Save bytes and open
  // ════════════════════════════════════════════
  static Future<String> _saveAndOpen(List<int> bytes, String fileName) async {
    if (kIsWeb) {
      await SharePlus.instance.share(
        ShareParams(
          files: [XFile.fromData(
            Uint8List.fromList(bytes),
            name: fileName,
          )],
        ),
      );
      return fileName;
    }

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(bytes);
    await OpenFile.open(file.path);
    return file.path;
  }
}