// Handles all 3 export types: Word, PDF, Plain Text

import 'dart:io';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import 'package:share_plus/share_plus.dart';

class ExportService {
  // ⚠️ CHANGE THIS to your PC's IP (the same one in api_service.dart)
  static const String _baseUrl = 'http://192.168.1.8:8000/api';


  // ════════════════════════════════════════════
  //  WORD EXPORT
  // ════════════════════════════════════════════
  static Future<String> exportAsWord({
    required String summary,
    required String filename,  // original PDF filename
  }) async {
    final response = await http.post(
      Uri.parse('$_baseUrl/export/word'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'summary': summary,
        'filename': filename,
      }),
    ).timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('Word export failed: ${response.statusCode}');
    }

    // Save to device storage
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/summary.docx');
    await file.writeAsBytes(response.bodyBytes);

    // Auto-open the file
    await OpenFile.open(file.path);
    return file.path;
  }


  // ════════════════════════════════════════════
  //  PDF EXPORT
  // ════════════════════════════════════════════
  static Future<String> exportAsPdf({
    required String summary,
    required String filename,
  }) async {
    final response = await http.post(
      Uri.parse('$_baseUrl/export/pdf'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'summary': summary,
        'filename': filename,
      }),
    ).timeout(const Duration(seconds: 30));

    if (response.statusCode != 200) {
      throw Exception('PDF export failed: ${response.statusCode}');
    }

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/summary.pdf');
    await file.writeAsBytes(response.bodyBytes);

    await OpenFile.open(file.path);
    return file.path;
  }


  // ════════════════════════════════════════════
  //  PLAIN TEXT EXPORT (no backend needed)
  // ════════════════════════════════════════════
  static Future<String> exportAsText({
    required String summary,
    required String filename,
  }) async {
    final now = DateTime.now();
    final content = '''DOCUMENT SUMMARY
================
Source File  : $filename
Generated On : ${now.day}/${now.month}/${now.year}  ${now.hour}:${now.minute.toString().padLeft(2,'0')}
Generated By : AI Office Assistant

SUMMARY
-------
$summary
''';

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/summary.txt');
    await file.writeAsString(content);

    // Open share sheet — user can save or WhatsApp or email it
    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Document Summary — $filename',
    );
    return file.path;
  }
}
